# Generated by Django 5.0.4 on 2024-05-04 16:17

import charidfield.fields
import django.db.models.deletion
import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', charidfield.fields.CharIDField(default=utils.models.cuid_default_value, help_text='cuid-format identifier for this entity.', max_length=225, prefix='chat_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', charidfield.fields.CharIDField(default=utils.models.cuid_default_value, help_text='cuid-format identifier for this entity.', max_length=225, prefix='message_', primary_key=True, serialize=False, unique=True)),
                ('creator', models.CharField(choices=[('user', 'heslb'), ('heslb', 'heslb')], max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtime_chat.chat')),
            ],
        ),
    ]
