# Generated by Django 5.0.4 on 2024-05-04 17:48

import charidfield.fields
import utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat', '0002_rename_message_chatmessage_rename_chat_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='chat',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=charidfield.fields.CharIDField(default=utils.models.cuid_default_value, help_text='cuid-format identifier for this entity.', max_length=225, prefix='room_', primary_key=True, serialize=False, unique=True),
        ),
    ]
