# Generated by Django 5.0.4 on 2024-06-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat', '0005_alter_chatroom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertUser',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('expert_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='creator',
            field=models.CharField(choices=[('user', 'user'), ('expert', 'expert')], max_length=50),
        ),
    ]
