# Generated by Django 5.0.4 on 2024-06-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_chat', '0006_expertuser_alter_chatmessage_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertuser',
            name='user_id',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
